name: Our first github actions

on: push 

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: echo a string
        run: echo "hello muthafucking world"

      - name: run multiline command
        run:  |
          npm -v
          node -v
      - name: run python shell command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-cmd-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
        - name: directory power shell
          run: Get-Location
        - name: bash command
          run: pwd
          shell: bash